### ISSUE TITLE
`ubuntu-latest` no longer available to download

### ISSUE THREAD

**Issue by timothytrippel** [chipsalliance/verible-actions-common#4]
The [OpenTitan project uses verible ](https://github.com/lowRISC/opentitan/blob/9601d3bbdd2e8862ad06d23184a980e92b2a3471/.github/workflows/pr_lint_review.yml#L20) and the [Verible linter action](https://github.com/chipsalliance/verible-linter-action/tree/main). We are getting errors when the action tries to download the tarball with the latest Verible built for Ubuntu:

<img width="822" alt="Screenshot 2023-12-20 at 1 52 46 PM" src="https://github.com/chipsalliance/verible-actions-common/assets/5633066/e8a4ff60-3f26-4740-85ca-0596c0c1bc2d">

It looks like the link is no longer valid.

**Comment by a-will** [comment]
Note: the distro-specific releases were removed in https://github.com/chipsalliance/verible/pull/2058. Perhaps this action should be adjusted to grab from the static release tarball?
